// Typesense API
//
// An open source search engine for building delightful search experiences.
//
// The version of the OpenAPI document: 27.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PresetUpsertSchemaValue {
	SearchParameters(Box<models::SearchParameters>),
	MultiSearchSearchesParameter(Box<models::MultiSearchSearchesParameter>),
}

impl Default for PresetUpsertSchemaValue {
	fn default() -> Self {
		Self::SearchParameters(Default::default())
	}
}
